// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CAvatar: typeof import('./../packages/components/avatar/src/index.vue')['default']
    CButton: typeof import('./../packages/components/button/src/index.vue')['default']
  }
}

export { }
